version: "3"

services:
  mysql:
    build: ./mariadb
    image: "mariadb:20190208"
    container_name: mariadb
    restart: always
    expose:
      - 3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=dbname
      - MYSQL_USER=username
      - MYSQL_PASSWORD=myPassword
      - MYSQL_ROOT_PASSWORD=rootPassword
    networks:
      - lemp

  php-fpm7:
    build: ./php-fpm7
    image: "php-fpm7:20190208"
    container_name: php-fpm7
    restart: always
    expose:
      - 9000
    volumes:
      - data:/data
    links:
      - mysql
    networks:
      - lemp

  nginx:
    build: ./nginx
    image: "nginx:20190208"
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - data:/data
    environment:
      - DOMAIN_NAME=example.com
      - EMAIL_ADDRESS=my@email.com
    links:
      - mysql
      - php-fpm7
    networks:
      - lemp

networks:
  lemp:
    driver: bridge

volumes:
  data:
  mysql_data:
