version: "3.5"

services:
  mysql:
    build: ./mysql
    image: "mysql:25072018"
    container_name: mysql
    restart: always
    expose:
      - 3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_USER=username
      - MYSQL_PASS=myPassword
      - DB_NAME=dbname
    networks:
      - lemp

  php7-fpm:
    build: ./php7-fpm
    image: "php7-fpm:25072018"
    container_name: php7-fpm
    restart: always
    expose:
      - 9000
    volumes:
      - data:/data
    links:
      - mysql
    networks:
      - lemp

  nginx:
    build: ./nginx
    image: "nginx:25072018"
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - data:/data
    environment:
      - FQDN=example.com
      - SUPPORT_SSL=no
    links:
      - mysql
      - php7-fpm
    networks:
      - lemp

networks:
  lemp:
    driver: bridge

volumes:
  data:
  mysql_data:
